{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcontactmethod\/message"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcontactmethod\/message"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod\/message","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"}],"title":"CinnoxVisitorContactMethod.message","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod@CinnoxVisitorContactMethodMessage","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorContactMethodMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorContactMethod":{"role":"symbol","title":"CinnoxVisitorContactMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorContactMethod"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorContactMethod"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcontactmethod"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorContactMethod/message":{"role":"symbol","title":"CinnoxVisitorContactMethod.message","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorContactMethodMessage"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcontactmethod\/message"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CinnoxVisitorContactMethodMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorContactMethodMessage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"CinnoxVisitorContactMethodMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod\/title","value":"CinnoxVisitorContactMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorContactMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod~1message\/title","value":"CinnoxVisitorContactMethodMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod~1message\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorContactMethodMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}