{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInitializationEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCoreError","text":"CinnoxVisitorCoreError"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"success","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"whether the initialization was successful."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"error if the initialization failed."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoredelegate\/oninitializationend(success:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoredelegate\/oninitializationend(success:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate\/onInitializationEnd(success:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delegation method to handle the end of initialization."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onInitializationEndWithSuccess:error:"}],"role":"symbol","title":"onInitializationEnd(success:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInitializationEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCoreError","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCoreError"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxVisitorCoreDelegate(im)onInitializationEndWithSuccess:error:","required":true,"modules":[{"name":"CinnoxVisitorCoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreDelegate/onInitializationEnd(success:error:)":{"navigatorTitle":[{"kind":"identifier","text":"onInitializationEndWithSuccess:error:"}],"role":"symbol","title":"onInitializationEnd(success:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInitializationEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCoreError","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCoreError"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Delegation method to handle the end of initialization."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate\/onInitializationEnd(success:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoredelegate\/oninitializationend(success:error:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreDelegate":{"role":"symbol","title":"CinnoxVisitorCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoredelegate"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreError":{"role":"symbol","title":"CinnoxVisitorCoreError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onInitializationEndWithSuccess:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInitializationEndWithSuccess:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onInitializationEndWithSuccess:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"success"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCoreError","text":"CinnoxVisitorCoreError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate~1onInitializationEnd(success:error:)\/title","value":"onInitializationEndWithSuccess:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate~1onInitializationEnd(success:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInitializationEndWithSuccess:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate\/title","value":"CinnoxVisitorCoreDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreError\/title","value":"CinnoxVisitorCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreError\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}