{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initDirectoryAction"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","text":"CinnoxAction"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"CinnoxDirectoryAction"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initdirectoryaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initdirectoryaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initDirectoryAction()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Init function to create directory action"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initDirectoryAction"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"title":"initDirectoryAction()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction(cm)initDirectoryAction","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initDirectoryAction"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction/initDirectoryAction()":{"role":"symbol","title":"initDirectoryAction()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initDirectoryAction"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"abstract":[{"type":"text","text":"Init function to create directory action"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initDirectoryAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initDirectoryAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initdirectoryaction()"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction":{"role":"symbol","title":"CinnoxAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"initDirectoryAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initDirectoryAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","text":"CinnoxAction"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"initDirectoryAction"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initDirectoryAction()\/title","value":"initDirectoryAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initDirectoryAction()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initDirectoryAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/title","value":"CinnoxAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/fragments","value":[{"kind":"identifier","text":"CinnoxAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}