{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initStaffAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"staffEid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contactMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod","text":"CinnoxVisitorContactMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","text":"CinnoxAction"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"CinnoxStaffAction"}]}]},{"kind":"parameters","parameters":[{"name":"staffEid","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"staff eid to be used for the action"}]}]},{"name":"contactMethod","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"contact method to be used for the action"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initstaffaction(staffeid:contactmethod:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initstaffaction(staffeid:contactmethod:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initStaffAction(staffEid:contactMethod:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Init function to create Staff Action instance"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initStaffAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"staffEid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contactMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorContactMethod","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"title":"initStaffAction(staffEid:contactMethod:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction(cm)initStaffActionWithStaffEid:contactMethod:","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initStaffActionWithStaffEid:contactMethod:"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction":{"role":"symbol","title":"CinnoxAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction/initStaffAction(staffEid:contactMethod:)":{"role":"symbol","title":"initStaffAction(staffEid:contactMethod:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initStaffAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"staffEid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contactMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorContactMethod","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"abstract":[{"type":"text","text":"Init function to create Staff Action instance"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initStaffAction(staffEid:contactMethod:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initStaffActionWithStaffEid:contactMethod:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initstaffaction(staffeid:contactmethod:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorContactMethod":{"role":"symbol","title":"CinnoxVisitorContactMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorContactMethod"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorContactMethod"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcontactmethod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"initStaffActionWithStaffEid:contactMethod:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initStaffActionWithStaffEid:contactMethod:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","text":"CinnoxAction"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"initStaffActionWithStaffEid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"staffEid"},{"kind":"text","text":" "},{"kind":"identifier","text":"contactMethod:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod","text":"CinnoxVisitorContactMethod"},{"kind":"text","text":")"},{"kind":"internalParam","text":"contactMethod"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/title","value":"CinnoxAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/fragments","value":[{"kind":"identifier","text":"CinnoxAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initStaffAction(staffEid:contactMethod:)\/title","value":"initStaffActionWithStaffEid:contactMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initStaffAction(staffEid:contactMethod:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initStaffActionWithStaffEid:contactMethod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod\/title","value":"CinnoxVisitorContactMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorContactMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}