{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UNNotificationRequest","preciseIdentifier":"c:objc(cs)UNNotificationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCinnoxContentHandler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contentHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonCinnoxContent"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler\/didreceive(_:withcinnoxcontenthandler:noncinnoxcontent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler\/didreceive(_:withcinnoxcontenthandler:noncinnoxcontent:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler\/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"}],"role":"symbol","title":"didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationRequest","preciseIdentifier":"c:objc(cs)UNNotificationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCinnoxContentHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonCinnoxContent"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler(im)didReceive:withCinnoxContentHandler:nonCinnoxContent:","required":true,"modules":[{"name":"CinnoxVisitorCoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxNotificationServiceHandler/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)":{"navigatorTitle":[{"kind":"identifier","text":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"}],"role":"symbol","title":"didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationRequest","preciseIdentifier":"c:objc(cs)UNNotificationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCinnoxContentHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonCinnoxContent"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler\/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler\/didreceive(_:withcinnoxcontenthandler:noncinnoxcontent:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxNotificationServiceHandler":{"role":"symbol","title":"CinnoxNotificationServiceHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceive:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationRequest","preciseIdentifier":"c:objc(cs)UNNotificationRequest"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"request"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCinnoxContentHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UNNotificationContent *)","preciseIdentifier":"c:BFv(#*$objc(cs)UNNotificationContent)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"contentHandler"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonCinnoxContent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":")"},{"kind":"internalParam","text":"nonCinnoxContent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler~1didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)\/title","value":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler~1didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/title","value":"CinnoxNotificationServiceHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/fragments","value":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}