{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler\/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"title":"CinnoxNotificationServiceHandler","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxNotificationServiceHandler":{"role":"symbol","title":"CinnoxNotificationServiceHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxNotificationServiceHandler/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)":{"navigatorTitle":[{"kind":"identifier","text":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"}],"role":"symbol","title":"didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UNNotificationRequest","preciseIdentifier":"c:objc(cs)UNNotificationRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withCinnoxContentHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UNNotificationContent","preciseIdentifier":"c:objc(cs)UNNotificationContent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonCinnoxContent"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler\/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler\/didreceive(_:withcinnoxcontenthandler:noncinnoxcontent:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CinnoxNotificationServiceHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler\/didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/title","value":"CinnoxNotificationServiceHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/fragments","value":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler~1didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)\/title","value":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler~1didReceive(_:withCinnoxContentHandler:nonCinnoxContent:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceive:withCinnoxContentHandler:nonCinnoxContent:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}