{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxDirectoryAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxStaffAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxTagAction"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject","doc:\/\/com.cinnox.visitor.core\/s7CVarArgP","doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/SQ","doc:\/\/com.cinnox.visitor.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initDirectoryAction()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initStaffAction(staffEid:contactMethod:)","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initTagAction(tagId:contactMethod:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"title":"CinnoxAction","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CinnoxAction"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxDirectoryAction":{"role":"symbol","title":"CinnoxDirectoryAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxDirectoryAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxDirectoryAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxDirectoryAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxdirectoryaction"},"doc://com.cinnox.visitor.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP"},"doc://com.cinnox.visitor.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(cs)NSObject"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction/initStaffAction(staffEid:contactMethod:)":{"role":"symbol","title":"initStaffAction(staffEid:contactMethod:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initStaffAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"staffEid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contactMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorContactMethod","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"abstract":[{"type":"text","text":"Init function to create Staff Action instance"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initStaffAction(staffEid:contactMethod:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initStaffActionWithStaffEid:contactMethod:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initstaffaction(staffeid:contactmethod:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction":{"role":"symbol","title":"CinnoxAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction/initDirectoryAction()":{"role":"symbol","title":"initDirectoryAction()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initDirectoryAction"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"abstract":[{"type":"text","text":"Init function to create directory action"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initDirectoryAction()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initDirectoryAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/initdirectoryaction()"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/init"},"doc://com.cinnox.visitor.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cinnox.visitor.core\/s7CVarArgP"},"doc://com.cinnox.visitor.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cinnox.visitor.core\/SQ"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction/initTagAction(tagId:contactMethod:)":{"role":"symbol","title":"initTagAction(tagId:contactMethod:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initTagAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tagId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"contactMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorContactMethod","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@E@CinnoxVisitorContactMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"}],"abstract":[{"type":"text","text":"Init function to create Tag Action instance"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initTagAction(tagId:contactMethod:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initTagActionWithTagId:contactMethod:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction\/inittagaction(tagid:contactmethod:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxTagAction":{"role":"symbol","title":"CinnoxTagAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxTagAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxTagAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxTagAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxtagaction"},"doc://com.cinnox.visitor.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject"},"doc://com.cinnox.visitor.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxStaffAction":{"role":"symbol","title":"CinnoxStaffAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxStaffAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxStaffAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxStaffAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxstaffaction"},"doc://com.cinnox.visitor.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cinnox.visitor.core\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CinnoxAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CinnoxAction"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CinnoxAction"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initDirectoryAction()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initStaffAction(staffEid:contactMethod:)","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction\/initTagAction(tagId:contactMethod:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxDirectoryAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxStaffAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxTagAction"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxDirectoryAction\/title","value":"CinnoxDirectoryAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxDirectoryAction\/fragments","value":[{"kind":"identifier","text":"CinnoxDirectoryAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initStaffAction(staffEid:contactMethod:)\/title","value":"initStaffActionWithStaffEid:contactMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initStaffAction(staffEid:contactMethod:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initStaffActionWithStaffEid:contactMethod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/title","value":"CinnoxAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/fragments","value":[{"kind":"identifier","text":"CinnoxAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initDirectoryAction()\/title","value":"initDirectoryAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initDirectoryAction()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initDirectoryAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initTagAction(tagId:contactMethod:)\/title","value":"initTagActionWithTagId:contactMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction~1initTagAction(tagId:contactMethod:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initTagActionWithTagId:contactMethod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxTagAction\/title","value":"CinnoxTagAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxTagAction\/fragments","value":[{"kind":"identifier","text":"CinnoxTagAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxStaffAction\/title","value":"CinnoxStaffAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxStaffAction\/fragments","value":[{"kind":"identifier","text":"CinnoxStaffAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}