{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorWidget"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(pl)NSCoding","doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject","doc:\/\/com.cinnox.visitor.core\/objc(pl)CALayerDelegate","doc:\/\/com.cinnox.visitor.core\/s7CVarArgP","doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/SQ","doc:\/\/com.cinnox.visitor.core\/SH","doc:\/\/com.cinnox.visitor.core\/s8SendableP","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIAppearance","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIAppearanceContainer","doc:\/\/com.cinnox.visitor.core\/objc(pl)UICoordinateSpace","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIDynamicItem","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIFocusEnvironment","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIFocusItem","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIFocusItemContainer","doc:\/\/com.cinnox.visitor.core\/objc(pl)UILargeContentViewerItem","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.cinnox.visitor.core\/objc(pl)UITraitEnvironment","doc:\/\/com.cinnox.visitor.core\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/init(frame:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/launch()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/layoutSubviews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorWidget"}],"title":"CinnoxVisitorWidget","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorWidget","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorWidget"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK"]]},"references":{"doc://com.cinnox.visitor.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cinnox.visitor.core\/SH"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorWidget/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget\/layoutsubviews()"},"doc://com.cinnox.visitor.core/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UILargeContentViewerItem"},"doc://com.cinnox.visitor.core/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIAppearanceContainer"},"doc://com.cinnox.visitor.core/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(cs)UIView"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorWidget/launch()":{"role":"symbol","title":"launch()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"launch"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/launch()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"launch"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget\/launch()"},"doc://com.cinnox.visitor.core/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIResponderStandardEditActions"},"doc://com.cinnox.visitor.core/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIUserActivityRestoring"},"doc://com.cinnox.visitor.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject"},"doc://com.cinnox.visitor.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorWidget/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget\/init(frame:)"},"doc://com.cinnox.visitor.core/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIFocusItem"},"doc://com.cinnox.visitor.core/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)CALayerDelegate"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UITraitEnvironment"},"doc://com.cinnox.visitor.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cinnox.visitor.core\/SQ"},"doc://com.cinnox.visitor.core/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorWidget":{"role":"symbol","title":"CinnoxVisitorWidget","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorWidget"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorWidget"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget"},"doc://com.cinnox.visitor.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cinnox.visitor.core\/s7CVarArgP"},"doc://com.cinnox.visitor.core/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSCoding"},"doc://com.cinnox.visitor.core/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIAccessibilityIdentification"},"doc://com.cinnox.visitor.core/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIFocusEnvironment"},"doc://com.cinnox.visitor.core/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIAppearance"},"doc://com.cinnox.visitor.core/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UICoordinateSpace"},"doc://com.cinnox.visitor.core/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIDynamicItem"},"doc://com.cinnox.visitor.core/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.cinnox.visitor.core/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.cinnox.visitor.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP"},"doc://com.cinnox.visitor.core/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)UIFocusItemContainer"},"doc://com.cinnox.visitor.core/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.cinnox.visitor.core\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CinnoxVisitorWidget"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorWidget"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CinnoxVisitorWidget"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/init(frame:)","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/launch()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget\/layoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorWidget"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget~1launch()\/title","value":"launch"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget~1launch()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"launch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget\/title","value":"CinnoxVisitorWidget"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorWidget"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}