{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CinnoxVisitorCoreError) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)NSError"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(pl)NSCoding","doc:\/\/com.cinnox.visitor.core\/objc(pl)NSCopying","doc:\/\/com.cinnox.visitor.core\/objc(pl)NSSecureCoding","doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject","doc:\/\/com.cinnox.visitor.core\/s7CVarArgP","doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/SQ","doc:\/\/com.cinnox.visitor.core\/s5ErrorP","doc:\/\/com.cinnox.visitor.core\/SH","doc:\/\/com.cinnox.visitor.core\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"title":"CinnoxVisitorCoreError","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCoreError","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK"]]},"references":{"doc://com.cinnox.visitor.core/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSSecureCoding"},"doc://com.cinnox.visitor.core/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.cinnox.visitor.core\/s8SendableP"},"doc://com.cinnox.visitor.core/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.cinnox.visitor.core\/s5ErrorP"},"doc://com.cinnox.visitor.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP"},"doc://com.cinnox.visitor.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cinnox.visitor.core\/SH"},"doc://com.cinnox.visitor.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cinnox.visitor.core\/SQ"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreError":{"role":"symbol","title":"CinnoxVisitorCoreError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror"},"doc://com.cinnox.visitor.core/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSCopying"},"doc://com.cinnox.visitor.core/objc(cs)NSError":{"type":"unresolvable","title":"NSError","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(cs)NSError"},"doc://com.cinnox.visitor.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreError/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror\/initwithcoder:"},"doc://com.cinnox.visitor.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreError/initWithDomain:code:userInfo:":{"role":"symbol","title":"initWithDomain:code:userInfo:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError\/initWithDomain:code:userInfo:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDomain:code:userInfo:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror\/initwithdomain:code:userinfo:"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSCoding"},"doc://com.cinnox.visitor.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cinnox.visitor.core\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CinnoxVisitorCoreError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}]},{"op":"add","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError\/initWithCoder:","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError\/initWithDomain:code:userInfo:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)NSError"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreError"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreError\/title","value":"CinnoxVisitorCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreError\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}