{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cinnox.visitor.core\/20LiveConnectUIKit_iOS0aB24CallFloatingViewDelegateP","doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject","doc:\/\/com.cinnox.visitor.core\/s7CVarArgP","doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP","doc:\/\/com.cinnox.visitor.core\/SQ","doc:\/\/com.cinnox.visitor.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/callToAction(action:completion:)","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/uninitialize()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/current"]},{"title":"Type Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/configure()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/createNotificationServiceHandler()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/initialize(serviceName:delegate:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/LiveConnectCallFloatingViewDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"title":"CinnoxVisitorCore","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/LiveConnectCallFloatingViewDelegate-Implementations":{"role":"collectionGroup","title":"LiveConnectCallFloatingViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/LiveConnectCallFloatingViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/liveconnectcallfloatingviewdelegate-implementations"},"doc://com.cinnox.visitor.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s28CustomDebugStringConvertibleP"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/createNotificationServiceHandler()":{"role":"symbol","title":"createNotificationServiceHandler()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNotificationServiceHandler"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CinnoxNotificationServiceHandler","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler"}],"abstract":[{"type":"text","text":"Creates an instance of "},{"type":"codeVoice","code":"CinnoxNotificationServiceHandler"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/createNotificationServiceHandler()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createNotificationServiceHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/createnotificationservicehandler()"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/callToAction(action:completion:)":{"role":"symbol","title":"callToAction(action:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callToAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCompletionHandler","preciseIdentifier":"s:20CinnoxVisitorCoreSDK0aB17CompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Trigger a call to action with given "},{"type":"codeVoice","code":"CinnoxAction"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/callToAction(action:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callToActionWithAction:completion:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/calltoaction(action:completion:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/uninitialize()":{"role":"symbol","title":"uninitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uninitialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Uninitalize current active "},{"type":"codeVoice","code":"CinnoxVisitorCore"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/uninitialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"uninitialize"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/uninitialize()"},"doc://com.cinnox.visitor.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cinnox.visitor.core\/SQ"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/current":{"role":"symbol","title":"current","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"current"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCore","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Instance of "},{"type":"codeVoice","code":"CinnoxVisitorCore"},{"type":"text","text":" that is currently active."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/current","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"current"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/current"},"doc://com.cinnox.visitor.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(pl)NSObject"},"doc://com.cinnox.visitor.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cinnox.visitor.core\/SH"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/configure()":{"role":"symbol","title":"configure()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Configure CinnoxVisitorCore"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/configure()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/configure()"},"doc://com.cinnox.visitor.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cinnox.visitor.core\/s23CustomStringConvertibleP"},"doc://com.cinnox.visitor.core/20LiveConnectUIKit_iOS0aB24CallFloatingViewDelegateP":{"type":"unresolvable","title":"LiveConnectUIKit_iOS.LiveConnectCallFloatingViewDelegate","identifier":"doc:\/\/com.cinnox.visitor.core\/20LiveConnectUIKit_iOS0aB24CallFloatingViewDelegateP"},"doc://com.cinnox.visitor.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.cinnox.visitor.core\/objc(cs)NSObject"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cinnox.visitor.core\/s7CVarArgP"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/initialize(serviceName:delegate:)":{"role":"symbol","title":"initialize(serviceName:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"serviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCoreDelegate","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxVisitorCoreDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxVisitorCore","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore"}],"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"CinnoxVisitorCore"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/initialize(serviceName:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithServiceName:delegate:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/initialize(servicename:delegate:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/callToAction(action:completion:)","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/uninitialize()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/current"]},{"title":"Type Methods","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/configure()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/createNotificationServiceHandler()","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/initialize(serviceName:delegate:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/LiveConnectCallFloatingViewDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cinnox.visitor.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1createNotificationServiceHandler()\/title","value":"createNotificationServiceHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1createNotificationServiceHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createNotificationServiceHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1callToAction(action:completion:)\/title","value":"callToActionWithAction:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1callToAction(action:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callToActionWithAction:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1uninitialize()\/title","value":"uninitialize"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1uninitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"uninitialize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1current\/title","value":"current"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1current\/fragments","value":[{"kind":"identifier","text":"current"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1configure()\/title","value":"configure"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1configure()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1initialize(serviceName:delegate:)\/title","value":"initializeWithServiceName:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1initialize(serviceName:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithServiceName:delegate:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}