{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callToAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","text":"CinnoxAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCompletionHandler","preciseIdentifier":"s:20CinnoxVisitorCoreSDK0aB17CompletionHandlera","text":"CinnoxVisitorCompletionHandler"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"action","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The action to be triggered."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion handler to be called when the action is completed with error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/calltoaction(action:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/calltoaction(action:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/callToAction(action:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Trigger a call to action with given "},{"type":"codeVoice","code":"CinnoxAction"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callToAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCompletionHandler","preciseIdentifier":"s:20CinnoxVisitorCoreSDK0aB17CompletionHandlera"},{"kind":"text","text":"?)"}],"title":"callToAction(action:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore(im)callToActionWithAction:completion:","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"callToActionWithAction:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction":{"role":"symbol","title":"CinnoxAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCompletionHandler":{"role":"symbol","title":"CinnoxVisitorCompletionHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCompletionHandler"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCompletionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCompletionHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcompletionhandler"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/callToAction(action:completion:)":{"role":"symbol","title":"callToAction(action:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"callToAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCompletionHandler","preciseIdentifier":"s:20CinnoxVisitorCoreSDK0aB17CompletionHandlera"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Trigger a call to action with given "},{"type":"codeVoice","code":"CinnoxAction"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/callToAction(action:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callToActionWithAction:completion:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/calltoaction(action:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"callToActionWithAction:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callToActionWithAction:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"callToActionWithAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxAction","text":"CinnoxAction"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"action"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(CinnoxVisitorCoreError *)","preciseIdentifier":"c:BFv(#*$@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCoreError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/title","value":"CinnoxAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/fragments","value":[{"kind":"identifier","text":"CinnoxAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1callToAction(action:completion:)\/title","value":"callToActionWithAction:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1callToAction(action:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callToActionWithAction:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}