{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CinnoxVisitorCore needs to be configured before calling other functions, This method should be called in AppDelegate’s "},{"type":"codeVoice","code":"didFinishLaunchingWithOptions"}]}],"type":"aside","name":"Requires"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/configure()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/configure()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/configure()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configure CinnoxVisitorCore"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"()"}],"title":"configure()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore(cm)configure","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"configure"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/configure()":{"role":"symbol","title":"configure()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Configure CinnoxVisitorCore"}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/configure()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/configure()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"configure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"configure"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1configure()\/title","value":"configure"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1configure()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}