{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNotificationServiceHandler"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler","text":"CinnoxNotificationServiceHandler"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"CinnoxNotificationServiceHandler"},{"type":"text","text":" instance"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This handler is designed to process notifications before any custom processing in a user’s own "},{"type":"codeVoice","code":"UNNotificationServiceExtension"},{"type":"text","text":". It ensures that Cinnox-specific notifications are handled appropriately, while non-Cinnox notifications can be managed by the user’s custom extensions."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/createnotificationservicehandler()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/createnotificationservicehandler()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/createNotificationServiceHandler()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates an instance of "},{"type":"codeVoice","code":"CinnoxNotificationServiceHandler"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNotificationServiceHandler"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CinnoxNotificationServiceHandler","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler"}],"title":"createNotificationServiceHandler()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore(cm)createNotificationServiceHandler","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"createNotificationServiceHandler"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/createNotificationServiceHandler()":{"role":"symbol","title":"createNotificationServiceHandler()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNotificationServiceHandler"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CinnoxNotificationServiceHandler","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler"}],"abstract":[{"type":"text","text":"Creates an instance of "},{"type":"codeVoice","code":"CinnoxNotificationServiceHandler"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/createNotificationServiceHandler()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createNotificationServiceHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/createnotificationservicehandler()"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxNotificationServiceHandler":{"role":"symbol","title":"CinnoxNotificationServiceHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createNotificationServiceHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createNotificationServiceHandler"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id<CinnoxNotificationServiceHandler>","preciseIdentifier":"c:Qo@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxNotificationServiceHandler"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createNotificationServiceHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1createNotificationServiceHandler()\/title","value":"createNotificationServiceHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1createNotificationServiceHandler()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createNotificationServiceHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/title","value":"CinnoxNotificationServiceHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/fragments","value":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}