{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresentCallFloatingView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isPresenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/didpresentcallfloatingview(ispresenting:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/didpresentcallfloatingview(ispresenting:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/didPresentCallFloatingView(isPresenting:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LiveConnectCallFloatingViewDelegate.didPresentCallFloatingView(isPresenting:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresentCallFloatingView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isPresenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"didPresentCallFloatingView(isPresenting:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore(im)didPresentCallFloatingViewWithIsPresenting:","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"didPresentCallFloatingViewWithIsPresenting:"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/LiveConnectCallFloatingViewDelegate-Implementations"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/LiveConnectCallFloatingViewDelegate-Implementations":{"role":"collectionGroup","title":"LiveConnectCallFloatingViewDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/LiveConnectCallFloatingViewDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/liveconnectcallfloatingviewdelegate-implementations"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/didPresentCallFloatingView(isPresenting:)":{"role":"symbol","title":"didPresentCallFloatingView(isPresenting:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresentCallFloatingView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isPresenting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/didPresentCallFloatingView(isPresenting:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didPresentCallFloatingViewWithIsPresenting:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/didpresentcallfloatingview(ispresenting:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didPresentCallFloatingViewWithIsPresenting:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPresentCallFloatingViewWithIsPresenting:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didPresentCallFloatingViewWithIsPresenting:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isPresenting"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1didPresentCallFloatingView(isPresenting:)\/title","value":"didPresentCallFloatingViewWithIsPresenting:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1didPresentCallFloatingView(isPresenting:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPresentCallFloatingViewWithIsPresenting:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}