{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"serviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxVisitorCoreDelegate","text":"CinnoxVisitorCoreDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore","text":"CinnoxVisitorCore"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A Initialized "},{"type":"codeVoice","code":"CinnoxVisitorCore"},{"type":"text","text":" instance."}]}]},{"kind":"parameters","parameters":[{"name":"serviceName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the service for which the core is being initialized."}]}]},{"name":"delegate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegate object that conforms to "},{"type":"codeVoice","code":"CinnoxVisitorCoreDelegate"},{"type":"text","text":" to receive callback events."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/initialize(servicename:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/initialize(servicename:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/initialize(serviceName:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"CinnoxVisitorCore"},{"type":"text","text":" instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"serviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCoreDelegate","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxVisitorCoreDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxVisitorCore","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore"}],"title":"initialize(serviceName:delegate:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore(cm)initializeWithServiceName:delegate:","modules":[{"name":"CinnoxVisitorCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithServiceName:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore"]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore/initialize(serviceName:delegate:)":{"role":"symbol","title":"initialize(serviceName:delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"serviceName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CinnoxVisitorCoreDelegate","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxVisitorCoreDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CinnoxVisitorCore","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore"}],"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"CinnoxVisitorCore"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore\/initialize(serviceName:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithServiceName:delegate:"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore\/initialize(servicename:delegate:)"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreDelegate":{"role":"symbol","title":"CinnoxVisitorCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoredelegate"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithServiceName:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithServiceName:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","preciseIdentifier":"c:@M@CinnoxVisitorCoreSDK@objc(cs)CinnoxVisitorCore","text":"CinnoxVisitorCore"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"initializeWithServiceName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"serviceName"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<CinnoxVisitorCoreDelegate>","preciseIdentifier":"c:Qo@M@CinnoxVisitorCoreSDK@objc(pl)CinnoxVisitorCoreDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1initialize(serviceName:delegate:)\/title","value":"initializeWithServiceName:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore~1initialize(serviceName:delegate:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithServiceName:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate\/title","value":"CinnoxVisitorCoreDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}