{"variants":[{"paths":["\/documentation\/cinnoxvisitorcoresdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/cinnoxvisitorcoresdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreSDK"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxDirectoryAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxStaffAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxTagAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget"]},{"title":"Protocols","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCompletionHandler"]},{"title":"Enumerations","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"CinnoxVisitorCoreSDK","title":"CinnoxVisitorCoreSDK","symbolKind":"module","role":"collection","modules":[{"name":"CinnoxVisitorCoreSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorContactMethod":{"role":"symbol","title":"CinnoxVisitorContactMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorContactMethod"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorContactMethod"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcontactmethod"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreError":{"role":"symbol","title":"CinnoxVisitorCoreError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreerror"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreVersionNumber":{"role":"symbol","title":"CinnoxVisitorCoreVersionNumber","fragments":[{"kind":"identifier","text":"CinnoxVisitorCoreVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for CinnoxVisitorCore."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreversionnumber"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCore":{"role":"symbol","title":"CinnoxVisitorCore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCore"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCore"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcore"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxAction":{"role":"symbol","title":"CinnoxAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxTagAction":{"role":"symbol","title":"CinnoxTagAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxTagAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxTagAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxTagAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxtagaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreDelegate":{"role":"symbol","title":"CinnoxVisitorCoreDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoredelegate"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreSDK":{"role":"article","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreSDK","kind":"article","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK":{"role":"collection","title":"CinnoxVisitorCoreSDK","abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxStaffAction":{"role":"symbol","title":"CinnoxStaffAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxStaffAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxStaffAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxStaffAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxstaffaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorWidget":{"role":"symbol","title":"CinnoxVisitorWidget","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorWidget"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorWidget"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorwidget"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCoreVersionString":{"role":"symbol","title":"CinnoxVisitorCoreVersionString","fragments":[{"kind":"identifier","text":"CinnoxVisitorCoreVersionString"}],"abstract":[{"type":"text","text":"Project version string for CinnoxVisitorCore."}],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreVersionString","kind":"symbol","type":"topic","url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcoreversionstring"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxVisitorCompletionHandler":{"role":"symbol","title":"CinnoxVisitorCompletionHandler","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxVisitorCompletionHandler"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCompletionHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxVisitorCompletionHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxvisitorcompletionhandler"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxDirectoryAction":{"role":"symbol","title":"CinnoxDirectoryAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxDirectoryAction"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxDirectoryAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxDirectoryAction"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxdirectoryaction"},"doc://com.cinnox.visitor.core/documentation/CinnoxVisitorCoreSDK/CinnoxNotificationServiceHandler":{"role":"symbol","title":"CinnoxNotificationServiceHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"abstract":[],"identifier":"doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}],"url":"\/documentation\/cinnoxvisitorcoresdk\/cinnoxnotificationservicehandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreSDK"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxDirectoryAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxStaffAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxTagAction","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCore","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreError","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorWidget"]},{"title":"Protocols","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxNotificationServiceHandler","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreVersionNumber","doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorCoreVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.cinnox.visitor.core\/documentation\/CinnoxVisitorCoreSDK\/CinnoxVisitorContactMethod"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod\/title","value":"CinnoxVisitorContactMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorContactMethod\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorContactMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreError\/title","value":"CinnoxVisitorCoreError"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreError\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/title","value":"CinnoxVisitorCore"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCore\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCore"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/title","value":"CinnoxAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxAction\/fragments","value":[{"kind":"identifier","text":"CinnoxAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxTagAction\/title","value":"CinnoxTagAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxTagAction\/fragments","value":[{"kind":"identifier","text":"CinnoxTagAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate\/title","value":"CinnoxVisitorCoreDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorCoreDelegate\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorCoreDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxStaffAction\/title","value":"CinnoxStaffAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxStaffAction\/fragments","value":[{"kind":"identifier","text":"CinnoxStaffAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget\/title","value":"CinnoxVisitorWidget"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxVisitorWidget\/fragments","value":[{"kind":"identifier","text":"CinnoxVisitorWidget"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxDirectoryAction\/title","value":"CinnoxDirectoryAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxDirectoryAction\/fragments","value":[{"kind":"identifier","text":"CinnoxDirectoryAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/title","value":"CinnoxNotificationServiceHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.cinnox.visitor.core~1documentation~1CinnoxVisitorCoreSDK~1CinnoxNotificationServiceHandler\/fragments","value":[{"kind":"identifier","text":"CinnoxNotificationServiceHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}